import { readFile, writeFile } from "fs/promises";
import { join } from "path";

/**
 * CSS Bundler for Obsidian ELN Plugin
 * 
 * This script reads all CSS files from src/styles/ and merges them
 * into a single styles.css file for the plugin.
 */

const cssDir = "./src/styles";
const outputFile = "./styles.css";

// CSS files in dependency order (base first, then components)
const cssFiles = [
    "base.css",
    "navbar.css", 
    "modals.css",
    "progress.css",
    "dashboard.css",
    "npe.css",
    "settings.css",
    "footer.css"
];

async function bundleCSS() {
    console.log("🎨 Bundling CSS files...");
    
    const cssContent = [
        "/*",
        "",
        "This CSS file will be included with your plugin, and",
        "available in the app when your plugin is enabled.",
        "",
        "If your plugin does not need CSS, delete this file.",
        "",
        "This file is automatically generated from src/styles/ by build-css.mjs",
        "Do not edit this file directly - edit the source files in src/styles/",
        "",
        "*/",
        ""
    ];

    for (const file of cssFiles) {
        const filePath = join(cssDir, file);
        try {
            const content = await readFile(filePath, "utf8");
            
            // Add section separator
            cssContent.push(`/* ===== ${file.replace('.css', '').toUpperCase()} ===== */`);
            cssContent.push("");
            cssContent.push(content.trim());
            cssContent.push("");
            
            console.log(`✓ Processed ${file}`);
        } catch (error) {
            console.warn(`⚠ Warning: Could not read ${file}:`, error.message);
        }
    }

    // Write the bundled CSS
    await writeFile(outputFile, cssContent.join("\n"));
    console.log(`✅ CSS bundled successfully to ${outputFile}`);
    
    // Calculate total size
    const stats = await readFile(outputFile);
    const sizeKB = (stats.length / 1024).toFixed(1);
    console.log(`📊 Total size: ${sizeKB} KB`);
}

async function main() {
    try {
        await bundleCSS();
    } catch (error) {
        console.error("❌ CSS bundling failed:", error);
        process.exit(1);
    }
}

main();
