// This file was generated by refactor-elements.js
export const elements = {
    "H": {
        "name": "Hydrogen",
        "atomicNumber": 1,
        "group": 1,
        "groupName": "nonmetal",
        "period": 1,
        "atomicMass": 1.008,
        "stability": "Stable",
        "isotopes": [
            "H-1",
            "H-2 (Deuterium)",
            "H-3 (Tritium)"
        ],
        "electronegativity": 2.2,
        "ionizationEnergies": [
            13.598
        ],
        "xrayAbsorptionEnergies": {
            "K": 13.6
        },
        "xrayEmissionEnergies": {}
    },
    "He": {
        "name": "Helium",
        "atomicNumber": 2,
        "group": 18,
        "groupName": "noble gas",
        "period": 1,
        "atomicMass": 4.0026,
        "stability": "Stable",
        "isotopes": [
            "He-3",
            "He-4"
        ],
        "electronegativity": null,
        "ionizationEnergies": [
            24.587
        ],
        "xrayAbsorptionEnergies": {
            "K": 24.6
        },
        "xrayEmissionEnergies": {}
    },
    "Li": {
        "name": "Lithium",
        "atomicNumber": 3,
        "group": 1,
        "groupName": "alkali metal",
        "period": 2,
        "atomicMass": 6.94,
        "stability": "Stable",
        "isotopes": [
            "Li-6",
            "Li-7"
        ],
        "electronegativity": 0.98,
        "ionizationEnergies": [
            5.391
        ],
        "xrayAbsorptionEnergies": {
            "K": 54.7
        },
        "xrayEmissionEnergies": {
            "Kα": 52,
            "Kβ": 59
        }
    },
    "Be": {
        "name": "Beryllium",
        "atomicNumber": 4,
        "group": 2,
        "groupName": "alkaline earth metal",
        "period": 2,
        "atomicMass": 9.0122,
        "stability": "Stable",
        "isotopes": [
            "Be-9"
        ],
        "electronegativity": 1.57,
        "ionizationEnergies": [
            9.322
        ],
        "xrayAbsorptionEnergies": {
            "K": 111.5
        },
        "xrayEmissionEnergies": {
            "Kα": 108.5,
            "Kβ": 118
        }
    },
    "B": {
        "name": "Boron",
        "atomicNumber": 5,
        "group": 13,
        "groupName": "metalloid",
        "period": 2,
        "atomicMass": 10.81,
        "stability": "Stable",
        "isotopes": [
            "B-10",
            "B-11"
        ],
        "electronegativity": 2.04,
        "ionizationEnergies": [
            8.298
        ],
        "xrayAbsorptionEnergies": {
            "K": 183.3
        },
        "xrayEmissionEnergies": {
            "Kα": 174,
            "Kβ": 192
        }
    },
    "C": {
        "name": "Carbon",
        "atomicNumber": 6,
        "group": 14,
        "groupName": "nonmetal",
        "period": 2,
        "atomicMass": 12.011,
        "stability": "Stable",
        "isotopes": [
            "C-12",
            "C-13",
            "C-14"
        ],
        "electronegativity": 2.55,
        "ionizationEnergies": [
            11.26
        ],
        "xrayAbsorptionEnergies": {
            "K": 284.2
        },
        "xrayEmissionEnergies": {
            "Kα": 277,
            "Kβ": 300
        }
    },
    "N": {
        "name": "Nitrogen",
        "atomicNumber": 7,
        "group": 15,
        "groupName": "nonmetal",
        "period": 2,
        "atomicMass": 14.007,
        "stability": "Stable",
        "isotopes": [
            "N-14",
            "N-15"
        ],
        "electronegativity": 3.04,
        "ionizationEnergies": [
            14.534
        ],
        "xrayAbsorptionEnergies": {
            "K": 409.9
        },
        "xrayEmissionEnergies": {
            "Kα": 392,
            "Kβ": 426
        }
    },
    "O": {
        "name": "Oxygen",
        "atomicNumber": 8,
        "group": 16,
        "groupName": "nonmetal",
        "period": 2,
        "atomicMass": 15.999,
        "stability": "Stable",
        "isotopes": [
            "O-16",
            "O-17",
            "O-18"
        ],
        "electronegativity": 3.44,
        "ionizationEnergies": [
            13.618
        ],
        "xrayAbsorptionEnergies": {
            "K": 543.1
        },
        "xrayEmissionEnergies": {
            "Kα": 525,
            "Kβ": 559
        }
    },
    "F": {
        "name": "Fluorine",
        "atomicNumber": 9,
        "group": 17,
        "groupName": "halogen",
        "period": 2,
        "atomicMass": 18.998,
        "stability": "Stable",
        "isotopes": [
            "F-19"
        ],
        "electronegativity": 3.98,
        "ionizationEnergies": [
            17.423
        ],
        "xrayAbsorptionEnergies": {
            "K": 696.7
        },
        "xrayEmissionEnergies": {
            "Kα": 677,
            "Kβ": 722
        }
    },
    "Ne": {
        "name": "Neon",
        "atomicNumber": 10,
        "group": 18,
        "groupName": "noble gas",
        "period": 2,
        "atomicMass": 20.18,
        "stability": "Stable",
        "isotopes": [
            "Ne-20",
            "Ne-21",
            "Ne-22"
        ],
        "electronegativity": null,
        "ionizationEnergies": [
            21.564
        ],
        "xrayAbsorptionEnergies": {
            "K": 870.2
        },
        "xrayEmissionEnergies": {
            "Kα": 848,
            "Kβ": 905
        }
    },
    "Na": {
        "name": "Sodium",
        "atomicNumber": 11,
        "group": 1,
        "groupName": "alkali metal",
        "period": 3,
        "atomicMass": 22.99,
        "stability": "Stable",
        "isotopes": [
            "Na-23"
        ],
        "electronegativity": 0.93,
        "ionizationEnergies": [
            5.139
        ],
        "xrayAbsorptionEnergies": {
            "K": 1070.8
        },
        "xrayEmissionEnergies": {
            "Kα": 1040,
            "Kβ": 1075
        }
    },
    "Mg": {
        "name": "Magnesium",
        "atomicNumber": 12,
        "group": 2,
        "groupName": "alkaline earth metal",
        "period": 3,
        "atomicMass": 24.305,
        "stability": "Stable",
        "isotopes": [
            "Mg-24",
            "Mg-25",
            "Mg-26"
        ],
        "electronegativity": 1.31,
        "ionizationEnergies": [
            7.646
        ],
        "xrayAbsorptionEnergies": {
            "K": 1303
        },
        "xrayEmissionEnergies": {
            "Kα": 1253,
            "Kβ": 1303
        }
    },
    "Al": {
        "name": "Aluminum",
        "atomicNumber": 13,
        "group": 13,
        "groupName": "post-transition metal",
        "period": 3,
        "atomicMass": 26.982,
        "stability": "Stable",
        "isotopes": [
            "Al-27"
        ],
        "electronegativity": 1.61,
        "ionizationEnergies": [
            5.986
        ],
        "xrayAbsorptionEnergies": {
            "K": 1559
        },
        "xrayEmissionEnergies": {
            "Kα": 1486,
            "Kβ": 1559
        }
    },
    "Si": {
        "name": "Silicon",
        "atomicNumber": 14,
        "group": 14,
        "groupName": "metalloid",
        "period": 3,
        "atomicMass": 28.085,
        "stability": "Stable",
        "isotopes": [
            "Si-28",
            "Si-29",
            "Si-30"
        ],
        "electronegativity": 1.9,
        "ionizationEnergies": [
            8.151
        ],
        "xrayAbsorptionEnergies": {
            "K": 1839
        },
        "xrayEmissionEnergies": {
            "Kα": 1739,
            "Kβ": 1839
        }
    },
    "P": {
        "name": "Phosphorus",
        "atomicNumber": 15,
        "group": 15,
        "groupName": "nonmetal",
        "period": 3,
        "atomicMass": 30.974,
        "stability": "Stable",
        "isotopes": [
            "P-31"
        ],
        "electronegativity": 2.19,
        "ionizationEnergies": [
            10.487
        ],
        "xrayAbsorptionEnergies": {
            "K": 2145.5
        },
        "xrayEmissionEnergies": {
            "Kα": 2010,
            "Kβ": 2145
        }
    },
    "S": {
        "name": "Sulfur",
        "atomicNumber": 16,
        "group": 16,
        "groupName": "nonmetal",
        "period": 3,
        "atomicMass": 32.06,
        "stability": "Stable",
        "isotopes": [
            "S-32",
            "S-33",
            "S-34",
            "S-36"
        ],
        "electronegativity": 2.58,
        "ionizationEnergies": [
            10.36
        ],
        "xrayAbsorptionEnergies": {
            "K": 2472
        },
        "xrayEmissionEnergies": {
            "Kα": 2307,
            "Kβ": 2472
        }
    },
    "Cl": {
        "name": "Chlorine",
        "atomicNumber": 17,
        "group": 17,
        "groupName": "halogen",
        "period": 3,
        "atomicMass": 35.45,
        "stability": "Stable",
        "isotopes": [
            "Cl-35",
            "Cl-37"
        ],
        "electronegativity": 3.16,
        "ionizationEnergies": [
            12.967
        ],
        "xrayAbsorptionEnergies": {
            "K": 2822
        },
        "xrayEmissionEnergies": {
            "Kα": 2622,
            "Kβ": 2822
        }
    },
    "Ar": {
        "name": "Argon",
        "atomicNumber": 18,
        "group": 18,
        "groupName": "noble gas",
        "period": 3,
        "atomicMass": 39.948,
        "stability": "Stable",
        "isotopes": [
            "Ar-36",
            "Ar-38",
            "Ar-40"
        ],
        "electronegativity": null,
        "ionizationEnergies": [
            15.76
        ],
        "xrayAbsorptionEnergies": {
            "K": 3205.9
        },
        "xrayEmissionEnergies": {
            "Kα": 2957,
            "Kβ": 3205
        }
    },
    "K": {
        "name": "Potassium",
        "atomicNumber": 19,
        "group": 1,
        "groupName": "alkali metal",
        "period": 4,
        "atomicMass": 39.098,
        "stability": "Stable",
        "isotopes": [
            "K-39",
            "K-40",
            "K-41"
        ],
        "electronegativity": 0.82,
        "ionizationEnergies": [
            4.341
        ],
        "xrayAbsorptionEnergies": {
            "K": 3608.4
        },
        "xrayEmissionEnergies": {
            "Kα": 3313,
            "Kβ": 3608
        }
    },
    "Ca": {
        "name": "Calcium",
        "atomicNumber": 20,
        "group": 2,
        "groupName": "alkaline earth metal",
        "period": 4,
        "atomicMass": 40.078,
        "stability": "Stable",
        "isotopes": [
            "Ca-40",
            "Ca-42",
            "Ca-43",
            "Ca-44",
            "Ca-46",
            "Ca-48"
        ],
        "electronegativity": 1,
        "ionizationEnergies": [
            6.113
        ],
        "xrayAbsorptionEnergies": {
            "K": 4038.5
        },
        "xrayEmissionEnergies": {
            "Kα": 3692,
            "Kβ": 4038
        }
    },
    "Sc": {
        "name": "Scandium",
        "atomicNumber": 21,
        "group": 3,
        "groupName": "transition metal",
        "period": 4,
        "atomicMass": 44.956,
        "stability": "Stable",
        "isotopes": [
            "Sc-45"
        ],
        "electronegativity": 1.36,
        "ionizationEnergies": [
            6.561
        ],
        "xrayAbsorptionEnergies": {
            "K": 4492
        },
        "xrayEmissionEnergies": {
            "Kα": 4102,
            "Kβ": 4492
        }
    },
    "Ti": {
        "name": "Titanium",
        "atomicNumber": 22,
        "group": 4,
        "groupName": "transition metal",
        "period": 4,
        "atomicMass": 47.867,
        "stability": "Stable",
        "isotopes": [
            "Ti-46",
            "Ti-47",
            "Ti-48",
            "Ti-49",
            "Ti-50"
        ],
        "electronegativity": 1.54,
        "ionizationEnergies": [
            6.828
        ],
        "xrayAbsorptionEnergies": {
            "K": 4966
        },
        "xrayEmissionEnergies": {
            "Kα": 4510,
            "Kβ": 4966
        }
    },
    "V": {
        "name": "Vanadium",
        "atomicNumber": 23,
        "group": 5,
        "groupName": "transition metal",
        "period": 4,
        "atomicMass": 50.942,
        "stability": "Stable",
        "isotopes": [
            "V-50",
            "V-51"
        ],
        "electronegativity": 1.63,
        "ionizationEnergies": [
            6.746
        ],
        "xrayAbsorptionEnergies": {
            "K": 5465
        },
        "xrayEmissionEnergies": {
            "Kα": 4950,
            "Kβ": 5465
        }
    },
    "Cr": {
        "name": "Chromium",
        "atomicNumber": 24,
        "group": 6,
        "groupName": "transition metal",
        "period": 4,
        "atomicMass": 51.996,
        "stability": "Stable",
        "isotopes": [
            "Cr-50",
            "Cr-52",
            "Cr-53",
            "Cr-54"
        ],
        "electronegativity": 1.66,
        "ionizationEnergies": [
            6.767
        ],
        "xrayAbsorptionEnergies": {
            "K": 5989
        },
        "xrayEmissionEnergies": {
            "Kα": 5415,
            "Kβ": 5989
        }
    },
    "Mn": {
        "name": "Manganese",
        "atomicNumber": 25,
        "group": 7,
        "groupName": "transition metal",
        "period": 4,
        "atomicMass": 54.938,
        "stability": "Stable",
        "isotopes": [
            "Mn-55"
        ],
        "electronegativity": 1.55,
        "ionizationEnergies": [
            7.434
        ],
        "xrayAbsorptionEnergies": {
            "K": 6539
        },
        "xrayEmissionEnergies": {
            "Kα": 5899,
            "Kβ": 6539
        }
    },
    "Fe": {
        "name": "Iron",
        "atomicNumber": 26,
        "group": 8,
        "groupName": "transition metal",
        "period": 4,
        "atomicMass": 55.845,
        "stability": "Stable",
        "isotopes": [
            "Fe-54",
            "Fe-56",
            "Fe-57",
            "Fe-58"
        ],
        "electronegativity": 1.83,
        "ionizationEnergies": [
            7.902
        ],
        "xrayAbsorptionEnergies": {
            "K": 7112
        },
        "xrayEmissionEnergies": {
            "Kα": 6403,
            "Kβ": 7058
        }
    },
    "Co": {
        "name": "Cobalt",
        "atomicNumber": 27,
        "group": 9,
        "groupName": "transition metal",
        "period": 4,
        "atomicMass": 58.933,
        "stability": "Stable",
        "isotopes": [
            "Co-59"
        ],
        "electronegativity": 1.88,
        "ionizationEnergies": [
            7.881
        ],
        "xrayAbsorptionEnergies": {
            "K": 7709
        },
        "xrayEmissionEnergies": {
            "Kα": 6930,
            "Kβ": 7709
        }
    },
    "Ni": {
        "name": "Nickel",
        "atomicNumber": 28,
        "group": 10,
        "groupName": "transition metal",
        "period": 4,
        "atomicMass": 58.693,
        "stability": "Stable",
        "isotopes": [
            "Ni-58",
            "Ni-60",
            "Ni-61",
            "Ni-62",
            "Ni-64"
        ],
        "electronegativity": 1.91,
        "ionizationEnergies": [
            7.64
        ],
        "xrayAbsorptionEnergies": {
            "K": 8333
        },
        "xrayEmissionEnergies": {
            "Kα": 7478,
            "Kβ": 8333
        }
    },
    "Cu": {
        "name": "Copper",
        "atomicNumber": 29,
        "group": 11,
        "groupName": "transition metal",
        "period": 4,
        "atomicMass": 63.546,
        "stability": "Stable",
        "isotopes": [
            "Cu-63",
            "Cu-65"
        ],
        "electronegativity": 1.9,
        "ionizationEnergies": [
            7.726
        ],
        "xrayAbsorptionEnergies": {
            "K": 8979
        },
        "xrayEmissionEnergies": {
            "Kα": 8047,
            "Kβ": 8979
        }
    },
    "Zn": {
        "name": "Zinc",
        "atomicNumber": 30,
        "group": 12,
        "groupName": "transition metal",
        "period": 4,
        "atomicMass": 65.38,
        "stability": "Stable",
        "isotopes": [
            "Zn-64",
            "Zn-66",
            "Zn-67",
            "Zn-68",
            "Zn-70"
        ],
        "electronegativity": 1.65,
        "ionizationEnergies": [
            9.394
        ],
        "xrayAbsorptionEnergies": {
            "K": 9659
        },
        "xrayEmissionEnergies": {
            "Kα": 8638,
            "Kβ": 9659
        }
    },
    "Ga": {
        "name": "Gallium",
        "atomicNumber": 31,
        "group": 13,
        "groupName": "post-transition metal",
        "period": 4,
        "atomicMass": 69.723,
        "stability": "Stable",
        "isotopes": [
            "Ga-69",
            "Ga-71"
        ],
        "electronegativity": 1.81,
        "ionizationEnergies": [
            5.999
        ],
        "xrayAbsorptionEnergies": {
            "K": 10367
        },
        "xrayEmissionEnergies": {
            "Kα": 9223,
            "Kβ": 10367
        }
    },
    "Ge": {
        "name": "Germanium",
        "atomicNumber": 32,
        "group": 14,
        "groupName": "metalloid",
        "period": 4,
        "atomicMass": 72.63,
        "stability": "Stable",
        "isotopes": [
            "Ge-70",
            "Ge-72",
            "Ge-73",
            "Ge-74",
            "Ge-76"
        ],
        "electronegativity": 2.01,
        "ionizationEnergies": [
            7.899
        ],
        "xrayAbsorptionEnergies": {
            "K": 11103
        },
        "xrayEmissionEnergies": {
            "Kα": 9886,
            "Kβ": 11103
        }
    },
    "As": {
        "name": "Arsenic",
        "atomicNumber": 33,
        "group": 15,
        "groupName": "metalloid",
        "period": 4,
        "atomicMass": 74.922,
        "stability": "Stable",
        "isotopes": [
            "As-75"
        ],
        "electronegativity": 2.18,
        "ionizationEnergies": [
            9.815
        ],
        "xrayAbsorptionEnergies": {
            "K": 11867
        },
        "xrayEmissionEnergies": {
            "Kα": 10544,
            "Kβ": 11867
        }
    },
    "Se": {
        "name": "Selenium",
        "atomicNumber": 34,
        "group": 16,
        "groupName": "nonmetal",
        "period": 4,
        "atomicMass": 78.971,
        "stability": "Stable",
        "isotopes": [
            "Se-74",
            "Se-76",
            "Se-77",
            "Se-78",
            "Se-80",
            "Se-82"
        ],
        "electronegativity": 2.55,
        "ionizationEnergies": [
            9.752
        ],
        "xrayAbsorptionEnergies": {
            "K": 12658
        },
        "xrayEmissionEnergies": {
            "Kα": 11225,
            "Kβ": 12658
        }
    },
    "Br": {
        "name": "Bromine",
        "atomicNumber": 35,
        "group": 17,
        "groupName": "halogen",
        "period": 4,
        "atomicMass": 79.904,
        "stability": "Stable",
        "isotopes": [
            "Br-79",
            "Br-81"
        ],
        "electronegativity": 2.96,
        "ionizationEnergies": [
            11.814
        ],
        "xrayAbsorptionEnergies": {
            "K": 13474
        },
        "xrayEmissionEnergies": {
            "Kα": 11925,
            "Kβ": 13474
        }
    },
    "Kr": {
        "name": "Krypton",
        "atomicNumber": 36,
        "group": 18,
        "groupName": "noble gas",
        "period": 4,
        "atomicMass": 83.798,
        "stability": "Stable",
        "isotopes": [
            "Kr-78",
            "Kr-80",
            "Kr-82",
            "Kr-83",
            "Kr-84",
            "Kr-86"
        ],
        "electronegativity": 3,
        "ionizationEnergies": [
            13.999
        ],
        "xrayAbsorptionEnergies": {
            "K": 14326
        },
        "xrayEmissionEnergies": {
            "Kα": 12658,
            "Kβ": 14326
        }
    },
    "Rb": {
        "name": "Rubidium",
        "atomicNumber": 37,
        "group": 1,
        "groupName": "alkali metal",
        "period": 5,
        "atomicMass": 85.468,
        "stability": "Stable",
        "isotopes": [
            "Rb-85",
            "Rb-87"
        ],
        "electronegativity": 0.82,
        "ionizationEnergies": [
            4.177
        ],
        "xrayAbsorptionEnergies": {
            "K": 15200
        },
        "xrayEmissionEnergies": {
            "Kα": 13390,
            "Kβ": 15200
        }
    },
    "Sr": {
        "name": "Strontium",
        "atomicNumber": 38,
        "group": 2,
        "groupName": "alkaline earth metal",
        "period": 5,
        "atomicMass": 87.62,
        "stability": "Stable",
        "isotopes": [
            "Sr-84",
            "Sr-86",
            "Sr-87",
            "Sr-88"
        ],
        "electronegativity": 0.95,
        "ionizationEnergies": [
            5.695
        ],
        "xrayAbsorptionEnergies": {
            "K": 16105
        },
        "xrayEmissionEnergies": {
            "Kα": 14100,
            "Kβ": 16105
        }
    },
    "Y": {
        "name": "Yttrium",
        "atomicNumber": 39,
        "group": 3,
        "groupName": "transition metal",
        "period": 5,
        "atomicMass": 88.906,
        "stability": "Stable",
        "isotopes": [
            "Y-89"
        ],
        "electronegativity": 1.22,
        "ionizationEnergies": [
            6.217
        ],
        "xrayAbsorptionEnergies": {
            "K": 17038
        },
        "xrayEmissionEnergies": {
            "Kα": 14900,
            "Kβ": 17038
        }
    },
    "Zr": {
        "name": "Zirconium",
        "atomicNumber": 40,
        "group": 4,
        "groupName": "transition metal",
        "period": 5,
        "atomicMass": 91.224,
        "stability": "Stable",
        "isotopes": [
            "Zr-90",
            "Zr-91",
            "Zr-92",
            "Zr-94",
            "Zr-96"
        ],
        "electronegativity": 1.33,
        "ionizationEnergies": [
            6.634
        ],
        "xrayAbsorptionEnergies": {
            "K": 17998
        },
        "xrayEmissionEnergies": {
            "Kα": 15800,
            "Kβ": 17998
        }
    },
    "Nb": {
        "name": "Niobium",
        "atomicNumber": 41,
        "group": 5,
        "groupName": "transition metal",
        "period": 5,
        "atomicMass": 92.906,
        "stability": "Stable",
        "isotopes": [
            "Nb-93"
        ],
        "electronegativity": 1.6,
        "ionizationEnergies": [
            6.759
        ],
        "xrayAbsorptionEnergies": {
            "K": 18986
        },
        "xrayEmissionEnergies": {
            "Kα": 16700,
            "Kβ": 18986
        }
    },
    "Mo": {
        "name": "Molybdenum",
        "atomicNumber": 42,
        "group": 6,
        "groupName": "transition metal",
        "period": 5,
        "atomicMass": 95.95,
        "stability": "Stable",
        "isotopes": [
            "Mo-92",
            "Mo-94",
            "Mo-95",
            "Mo-96",
            "Mo-97",
            "Mo-98",
            "Mo-100"
        ],
        "electronegativity": 2.16,
        "ionizationEnergies": [
            7.092
        ],
        "xrayAbsorptionEnergies": {
            "K": 20000
        },
        "xrayEmissionEnergies": {
            "Kα": 17400,
            "Kβ": 20000
        }
    },
    "Tc": {
        "name": "Technetium",
        "atomicNumber": 43,
        "group": 7,
        "groupName": "transition metal",
        "period": 5,
        "atomicMass": 98,
        "stability": "Radioactive",
        "isotopes": [
            "Tc-97",
            "Tc-98",
            "Tc-99"
        ],
        "electronegativity": 1.9,
        "ionizationEnergies": [
            7.28
        ],
        "xrayAbsorptionEnergies": {
            "K": 21044
        },
        "xrayEmissionEnergies": {
            "Kα": 18200,
            "Kβ": 21044
        }
    },
    "Ru": {
        "name": "Ruthenium",
        "atomicNumber": 44,
        "group": 8,
        "groupName": "transition metal",
        "period": 5,
        "atomicMass": 101.07,
        "stability": "Stable",
        "isotopes": [
            "Ru-96",
            "Ru-98",
            "Ru-99",
            "Ru-100",
            "Ru-101",
            "Ru-102",
            "Ru-104"
        ],
        "electronegativity": 2.2,
        "ionizationEnergies": [
            7.36
        ],
        "xrayAbsorptionEnergies": {
            "K": 22117
        },
        "xrayEmissionEnergies": {
            "Kα": 19200,
            "Kβ": 22117
        }
    },
    "Rh": {
        "name": "Rhodium",
        "atomicNumber": 45,
        "group": 9,
        "groupName": "transition metal",
        "period": 5,
        "atomicMass": 102.91,
        "stability": "Stable",
        "isotopes": [
            "Rh-103"
        ],
        "electronegativity": 2.28,
        "ionizationEnergies": [
            7.46
        ],
        "xrayAbsorptionEnergies": {
            "K": 23220
        },
        "xrayEmissionEnergies": {
            "Kα": 20200,
            "Kβ": 23220
        }
    },
    "Pd": {
        "name": "Palladium",
        "atomicNumber": 46,
        "group": 10,
        "groupName": "transition metal",
        "period": 5,
        "atomicMass": 106.42,
        "stability": "Stable",
        "isotopes": [
            "Pd-102",
            "Pd-104",
            "Pd-105",
            "Pd-106",
            "Pd-108",
            "Pd-110"
        ],
        "electronegativity": 2.2,
        "ionizationEnergies": [
            8.34
        ],
        "xrayAbsorptionEnergies": {
            "K": 24350
        },
        "xrayEmissionEnergies": {
            "Kα": 21400,
            "Kβ": 24350
        }
    },
    "Ag": {
        "name": "Silver",
        "atomicNumber": 47,
        "group": 11,
        "groupName": "transition metal",
        "period": 5,
        "atomicMass": 107.87,
        "stability": "Stable",
        "isotopes": [
            "Ag-107",
            "Ag-109"
        ],
        "electronegativity": 1.93,
        "ionizationEnergies": [
            7.576
        ],
        "xrayAbsorptionEnergies": {
            "K": 25514
        },
        "xrayEmissionEnergies": {
            "Kα": 22600,
            "Kβ": 25514
        }
    },
    "Cd": {
        "name": "Cadmium",
        "atomicNumber": 48,
        "group": 12,
        "groupName": "transition metal",
        "period": 5,
        "atomicMass": 112.41,
        "stability": "Stable",
        "isotopes": [
            "Cd-106",
            "Cd-108",
            "Cd-110",
            "Cd-111",
            "Cd-112",
            "Cd-113",
            "Cd-114",
            "Cd-116"
        ],
        "electronegativity": 1.69,
        "ionizationEnergies": [
            8.993
        ],
        "xrayAbsorptionEnergies": {
            "K": 26711
        },
        "xrayEmissionEnergies": {
            "Kα": 23900,
            "Kβ": 26711
        }
    },
    "In": {
        "name": "Indium",
        "atomicNumber": 49,
        "group": 13,
        "groupName": "post-transition metal",
        "period": 5,
        "atomicMass": 114.82,
        "stability": "Stable",
        "isotopes": [
            "In-113",
            "In-115"
        ],
        "electronegativity": 1.78,
        "ionizationEnergies": [
            5.786
        ],
        "xrayAbsorptionEnergies": {
            "K": 27940
        },
        "xrayEmissionEnergies": {
            "Kα": 25200,
            "Kβ": 27940
        }
    },
    "Sn": {
        "name": "Tin",
        "atomicNumber": 50,
        "group": 14,
        "groupName": "post-transition metal",
        "period": 5,
        "atomicMass": 118.71,
        "stability": "Stable",
        "isotopes": [
            "Sn-112",
            "Sn-114",
            "Sn-115",
            "Sn-116",
            "Sn-117",
            "Sn-118",
            "Sn-119",
            "Sn-120",
            "Sn-122",
            "Sn-124"
        ],
        "electronegativity": 1.96,
        "ionizationEnergies": [
            7.344
        ],
        "xrayAbsorptionEnergies": {
            "K": 29200
        },
        "xrayEmissionEnergies": {
            "Kα": 26500,
            "Kβ": 29200
        }
    },
    "Sb": {
        "name": "Antimony",
        "atomicNumber": 51,
        "group": 15,
        "groupName": "metalloid",
        "period": 5,
        "atomicMass": 121.76,
        "stability": "Stable",
        "isotopes": [
            "Sb-121",
            "Sb-123"
        ],
        "electronegativity": 2.05,
        "ionizationEnergies": [
            8.608
        ],
        "xrayAbsorptionEnergies": {
            "K": 30491
        },
        "xrayEmissionEnergies": {
            "Kα": 27600,
            "Kβ": 30491
        }
    },
    "Te": {
        "name": "Tellurium",
        "atomicNumber": 52,
        "group": 16,
        "groupName": "metalloid",
        "period": 5,
        "atomicMass": 127.6,
        "stability": "Stable",
        "isotopes": [
            "Te-120",
            "Te-122",
            "Te-123",
            "Te-124",
            "Te-125",
            "Te-126",
            "Te-128",
            "Te-130"
        ],
        "electronegativity": 2.1,
        "ionizationEnergies": [
            9.009
        ],
        "xrayAbsorptionEnergies": {
            "K": 31781
        },
        "xrayEmissionEnergies": {
            "Kα": 28700,
            "Kβ": 31781
        }
    },
    "I": {
        "name": "Iodine",
        "atomicNumber": 53,
        "group": 17,
        "groupName": "halogen",
        "period": 5,
        "atomicMass": 126.9,
        "stability": "Stable",
        "isotopes": [
            "I-127"
        ],
        "electronegativity": 2.66,
        "ionizationEnergies": [
            10.451
        ],
        "xrayAbsorptionEnergies": {
            "K": 33169
        },
        "xrayEmissionEnergies": {
            "Kα": 29800,
            "Kβ": 33169
        }
    },
    "Xe": {
        "name": "Xenon",
        "atomicNumber": 54,
        "group": 18,
        "groupName": "noble gas",
        "period": 5,
        "atomicMass": 131.29,
        "stability": "Stable",
        "isotopes": [
            "Xe-124",
            "Xe-126",
            "Xe-128",
            "Xe-129",
            "Xe-130",
            "Xe-131",
            "Xe-132",
            "Xe-134",
            "Xe-136"
        ],
        "electronegativity": 2.6,
        "ionizationEnergies": [
            12.13
        ],
        "xrayAbsorptionEnergies": {
            "K": 34649
        },
        "xrayEmissionEnergies": {
            "Kα": 31100,
            "Kβ": 34649
        }
    },
    "Cs": {
        "name": "Cesium",
        "atomicNumber": 55,
        "group": 1,
        "groupName": "alkali metal",
        "period": 6,
        "atomicMass": 132.91,
        "stability": "Stable",
        "isotopes": [
            "Cs-133"
        ],
        "electronegativity": 0.79,
        "ionizationEnergies": [
            3.894
        ],
        "xrayAbsorptionEnergies": {
            "K": 36199
        },
        "xrayEmissionEnergies": {
            "Kα": 32400,
            "Kβ": 36199
        }
    },
    "Ba": {
        "name": "Barium",
        "atomicNumber": 56,
        "group": 2,
        "groupName": "alkaline earth metal",
        "period": 6,
        "atomicMass": 137.33,
        "stability": "Stable",
        "isotopes": [
            "Ba-130",
            "Ba-132",
            "Ba-134",
            "Ba-135",
            "Ba-136",
            "Ba-137",
            "Ba-138"
        ],
        "electronegativity": 0.89,
        "ionizationEnergies": [
            5.212
        ],
        "xrayAbsorptionEnergies": {
            "K": 37815
        },
        "xrayEmissionEnergies": {
            "Kα": 33800,
            "Kβ": 37815
        }
    },
    "La": {
        "name": "Lanthanum",
        "atomicNumber": 57,
        "group": "La-1",
        "groupName": "lanthanide",
        "period": 6,
        "atomicMass": 138.91,
        "stability": "Stable",
        "isotopes": [
            "La-138",
            "La-139"
        ],
        "electronegativity": 1.1,
        "ionizationEnergies": [
            5.577
        ],
        "xrayAbsorptionEnergies": {
            "K": 39400
        },
        "xrayEmissionEnergies": {
            "Kα": 35200,
            "Kβ": 39400
        }
    },
    "Ce": {
        "name": "Cerium",
        "atomicNumber": 58,
        "group": "La-2",
        "groupName": "lanthanide",
        "period": 6,
        "atomicMass": 140.12,
        "stability": "Stable",
        "isotopes": [
            "Ce-136",
            "Ce-138",
            "Ce-140",
            "Ce-142"
        ],
        "electronegativity": 1.12,
        "ionizationEnergies": [
            5.538
        ],
        "xrayAbsorptionEnergies": {
            "K": 41000
        },
        "xrayEmissionEnergies": {
            "Kα": 36600,
            "Kβ": 41000
        }
    },
    "Pr": {
        "name": "Praseodymium",
        "atomicNumber": 59,
        "group": "La-3",
        "groupName": "lanthanide",
        "period": 6,
        "atomicMass": 140.91,
        "stability": "Stable",
        "isotopes": [
            "Pr-141"
        ],
        "electronegativity": 1.13,
        "ionizationEnergies": [
            5.473
        ],
        "xrayAbsorptionEnergies": {
            "K": 42700
        },
        "xrayEmissionEnergies": {
            "Kα": 38000,
            "Kβ": 42700
        }
    },
    "Nd": {
        "name": "Neodymium",
        "atomicNumber": 60,
        "group": "La-4",
        "groupName": "lanthanide",
        "period": 6,
        "atomicMass": 144.24,
        "stability": "Stable",
        "isotopes": [
            "Nd-142",
            "Nd-143",
            "Nd-144",
            "Nd-145",
            "Nd-146",
            "Nd-148",
            "Nd-150"
        ],
        "electronegativity": 1.14,
        "ionizationEnergies": [
            5.525
        ],
        "xrayAbsorptionEnergies": {
            "K": 44400
        },
        "xrayEmissionEnergies": {
            "Kα": 39500,
            "Kβ": 44400
        }
    },
    "Pm": {
        "name": "Promethium",
        "atomicNumber": 61,
        "group": "La-5",
        "groupName": "lanthanide",
        "period": 6,
        "atomicMass": 145,
        "stability": "Radioactive",
        "isotopes": [
            "Pm-145"
        ],
        "electronegativity": 1.13,
        "ionizationEnergies": [
            5.582
        ],
        "xrayAbsorptionEnergies": {
            "K": 46100
        },
        "xrayEmissionEnergies": {
            "Kα": 41000,
            "Kβ": 46100
        }
    },
    "Sm": {
        "name": "Samarium",
        "atomicNumber": 62,
        "group": "La-6",
        "groupName": "lanthanide",
        "period": 6,
        "atomicMass": 150.36,
        "stability": "Stable",
        "isotopes": [
            "Sm-144",
            "Sm-147",
            "Sm-148",
            "Sm-149",
            "Sm-150",
            "Sm-152",
            "Sm-154"
        ],
        "electronegativity": 1.17,
        "ionizationEnergies": [
            5.643
        ],
        "xrayAbsorptionEnergies": {
            "K": 47800
        },
        "xrayEmissionEnergies": {
            "Kα": 42500,
            "Kβ": 47800
        }
    },
    "Eu": {
        "name": "Europium",
        "atomicNumber": 63,
        "group": "La-7",
        "groupName": "lanthanide",
        "period": 6,
        "atomicMass": 151.96,
        "stability": "Stable",
        "isotopes": [
            "Eu-151",
            "Eu-153"
        ],
        "electronegativity": 1.2,
        "ionizationEnergies": [
            5.67
        ],
        "xrayAbsorptionEnergies": {
            "K": 49600
        },
        "xrayEmissionEnergies": {
            "Kα": 44000,
            "Kβ": 49600
        }
    },
    "Gd": {
        "name": "Gadolinium",
        "atomicNumber": 64,
        "group": "La-8",
        "groupName": "lanthanide",
        "period": 6,
        "atomicMass": 157.25,
        "stability": "Stable",
        "isotopes": [
            "Gd-152",
            "Gd-154",
            "Gd-155",
            "Gd-156",
            "Gd-157",
            "Gd-158",
            "Gd-160"
        ],
        "electronegativity": 1.2,
        "ionizationEnergies": [
            6.15
        ],
        "xrayAbsorptionEnergies": {
            "K": 51400
        },
        "xrayEmissionEnergies": {
            "Kα": 45500,
            "Kβ": 51400
        }
    },
    "Tb": {
        "name": "Terbium",
        "atomicNumber": 65,
        "group": "La-9",
        "groupName": "lanthanide",
        "period": 6,
        "atomicMass": 158.93,
        "stability": "Stable",
        "isotopes": [
            "Tb-159"
        ],
        "electronegativity": 1.2,
        "ionizationEnergies": [
            5.863
        ],
        "xrayAbsorptionEnergies": {
            "K": 53300
        },
        "xrayEmissionEnergies": {
            "Kα": 47000,
            "Kβ": 53300
        }
    },
    "Dy": {
        "name": "Dysprosium",
        "atomicNumber": 66,
        "group": "La-10",
        "groupName": "lanthanide",
        "period": 6,
        "atomicMass": 162.5,
        "stability": "Stable",
        "isotopes": [
            "Dy-156",
            "Dy-158",
            "Dy-160",
            "Dy-161",
            "Dy-162",
            "Dy-163",
            "Dy-164"
        ],
        "electronegativity": 1.22,
        "ionizationEnergies": [
            5.938
        ],
        "xrayAbsorptionEnergies": {
            "K": 55200
        },
        "xrayEmissionEnergies": {
            "Kα": 48500,
            "Kβ": 55200
        }
    },
    "Ho": {
        "name": "Holmium",
        "atomicNumber": 67,
        "group": "La-11",
        "groupName": "lanthanide",
        "period": 6,
        "atomicMass": 164.93,
        "stability": "Stable",
        "isotopes": [
            "Ho-165"
        ],
        "electronegativity": 1.23,
        "ionizationEnergies": [
            6.022
        ],
        "xrayAbsorptionEnergies": {
            "K": 57100
        },
        "xrayEmissionEnergies": {
            "Kα": 50000,
            "Kβ": 57100
        }
    },
    "Er": {
        "name": "Erbium",
        "atomicNumber": 68,
        "group": "La-12",
        "groupName": "lanthanide",
        "period": 6,
        "atomicMass": 167.26,
        "stability": "Stable",
        "isotopes": [
            "Er-162",
            "Er-164",
            "Er-166",
            "Er-167",
            "Er-168",
            "Er-170"
        ],
        "electronegativity": 1.24,
        "ionizationEnergies": [
            6.108
        ],
        "xrayAbsorptionEnergies": {
            "K": 59000
        },
        "xrayEmissionEnergies": {
            "Kα": 51500,
            "Kβ": 59000
        }
    },
    "Tm": {
        "name": "Thulium",
        "atomicNumber": 69,
        "group": "La-13",
        "groupName": "lanthanide",
        "period": 6,
        "atomicMass": 168.93,
        "stability": "Stable",
        "isotopes": [
            "Tm-169"
        ],
        "electronegativity": 1.25,
        "ionizationEnergies": [
            6.184
        ],
        "xrayAbsorptionEnergies": {
            "K": 61000
        },
        "xrayEmissionEnergies": {
            "Kα": 53000,
            "Kβ": 61000
        }
    },
    "Yb": {
        "name": "Ytterbium",
        "atomicNumber": 70,
        "group": "La-14",
        "groupName": "lanthanide",
        "period": 6,
        "atomicMass": 173.05,
        "stability": "Stable",
        "isotopes": [
            "Yb-168",
            "Yb-170",
            "Yb-171",
            "Yb-172",
            "Yb-173",
            "Yb-174",
            "Yb-176"
        ],
        "electronegativity": 1.1,
        "ionizationEnergies": [
            6.254
        ],
        "xrayAbsorptionEnergies": {
            "K": 63000
        },
        "xrayEmissionEnergies": {
            "Kα": 54500,
            "Kβ": 63000
        }
    },
    "Lu": {
        "name": "Lutetium",
        "atomicNumber": 71,
        "group": "La-15",
        "groupName": "lanthanide",
        "period": 6,
        "atomicMass": 174.97,
        "stability": "Stable",
        "isotopes": [
            "Lu-175",
            "Lu-176"
        ],
        "electronegativity": 1.27,
        "ionizationEnergies": [
            5.426
        ],
        "xrayAbsorptionEnergies": {
            "K": 65100
        },
        "xrayEmissionEnergies": {
            "Kα": 56000,
            "Kβ": 65100
        }
    },
    "Hf": {
        "name": "Hafnium",
        "atomicNumber": 72,
        "group": 4,
        "groupName": "transition metal",
        "period": 6,
        "atomicMass": 178.49,
        "stability": "Stable",
        "isotopes": [
            "Hf-174",
            "Hf-176",
            "Hf-177",
            "Hf-178",
            "Hf-179",
            "Hf-180"
        ],
        "electronegativity": 1.3,
        "ionizationEnergies": [
            6.825
        ],
        "xrayAbsorptionEnergies": {
            "K": 68400
        },
        "xrayEmissionEnergies": {
            "Kα": 59000,
            "Kβ": 68400
        }
    },
    "Ta": {
        "name": "Tantalum",
        "atomicNumber": 73,
        "group": 5,
        "groupName": "transition metal",
        "period": 6,
        "atomicMass": 180.95,
        "stability": "Stable",
        "isotopes": [
            "Ta-180",
            "Ta-181"
        ],
        "electronegativity": 1.5,
        "ionizationEnergies": [
            7.549
        ],
        "xrayAbsorptionEnergies": {
            "K": 71800
        },
        "xrayEmissionEnergies": {
            "Kα": 62000,
            "Kβ": 71800
        }
    },
    "W": {
        "name": "Tungsten",
        "atomicNumber": 74,
        "group": 6,
        "groupName": "transition metal",
        "period": 6,
        "atomicMass": 183.84,
        "stability": "Stable",
        "isotopes": [
            "W-180",
            "W-182",
            "W-183",
            "W-184",
            "W-186"
        ],
        "electronegativity": 2.36,
        "ionizationEnergies": [
            7.864
        ],
        "xrayAbsorptionEnergies": {
            "K": 75300
        },
        "xrayEmissionEnergies": {
            "Kα": 65000,
            "Kβ": 75300
        }
    },
    "Re": {
        "name": "Rhenium",
        "atomicNumber": 75,
        "group": 7,
        "groupName": "transition metal",
        "period": 6,
        "atomicMass": 186.21,
        "stability": "Stable",
        "isotopes": [
            "Re-185",
            "Re-187"
        ],
        "electronegativity": 1.9,
        "ionizationEnergies": [
            7.833
        ],
        "xrayAbsorptionEnergies": {
            "K": 78900
        },
        "xrayEmissionEnergies": {
            "Kα": 68000,
            "Kβ": 78900
        }
    },
    "Os": {
        "name": "Osmium",
        "atomicNumber": 76,
        "group": 8,
        "groupName": "transition metal",
        "period": 6,
        "atomicMass": 190.23,
        "stability": "Stable",
        "isotopes": [
            "Os-184",
            "Os-186",
            "Os-187",
            "Os-188",
            "Os-189",
            "Os-190",
            "Os-192"
        ],
        "electronegativity": 2.2,
        "ionizationEnergies": [
            8.438
        ],
        "xrayAbsorptionEnergies": {
            "K": 82600
        },
        "xrayEmissionEnergies": {
            "Kα": 71000,
            "Kβ": 82600
        }
    },
    "Ir": {
        "name": "Iridium",
        "atomicNumber": 77,
        "group": 9,
        "groupName": "transition metal",
        "period": 6,
        "atomicMass": 192.22,
        "stability": "Stable",
        "isotopes": [
            "Ir-191",
            "Ir-193"
        ],
        "electronegativity": 2.2,
        "ionizationEnergies": [
            8.967
        ],
        "xrayAbsorptionEnergies": {
            "K": 86400
        },
        "xrayEmissionEnergies": {
            "Kα": 74000,
            "Kβ": 86400
        }
    },
    "Pt": {
        "name": "Platinum",
        "atomicNumber": 78,
        "group": 10,
        "groupName": "transition metal",
        "period": 6,
        "atomicMass": 195.08,
        "stability": "Stable",
        "isotopes": [
            "Pt-190",
            "Pt-192",
            "Pt-194",
            "Pt-195",
            "Pt-196",
            "Pt-198"
        ],
        "electronegativity": 2.28,
        "ionizationEnergies": [
            8.958
        ],
        "xrayAbsorptionEnergies": {
            "K": 90300
        },
        "xrayEmissionEnergies": {
            "Kα": 77000,
            "Kβ": 90300
        }
    },
    "Au": {
        "name": "Gold",
        "atomicNumber": 79,
        "group": 11,
        "groupName": "transition metal",
        "period": 6,
        "atomicMass": 196.97,
        "stability": "Stable",
        "isotopes": [
            "Au-197"
        ],
        "electronegativity": 2.54,
        "ionizationEnergies": [
            9.225
        ],
        "xrayAbsorptionEnergies": {
            "K": 94200
        },
        "xrayEmissionEnergies": {
            "Kα": 80000,
            "Kβ": 94200
        }
    },
    "Hg": {
        "name": "Mercury",
        "atomicNumber": 80,
        "group": 12,
        "groupName": "transition metal",
        "period": 6,
        "atomicMass": 200.59,
        "stability": "Stable",
        "isotopes": [
            "Hg-196",
            "Hg-198",
            "Hg-199",
            "Hg-200",
            "Hg-201",
            "Hg-202",
            "Hg-204"
        ],
        "electronegativity": 2,
        "ionizationEnergies": [
            10.437
        ],
        "xrayAbsorptionEnergies": {
            "K": 98300
        },
        "xrayEmissionEnergies": {
            "Kα": 83000,
            "Kβ": 98300
        }
    },
    "Tl": {
        "name": "Thallium",
        "atomicNumber": 81,
        "group": 13,
        "groupName": "post-transition metal",
        "period": 6,
        "atomicMass": 204.38,
        "stability": "Stable",
        "isotopes": [
            "Tl-203",
            "Tl-205"
        ],
        "electronegativity": 1.62,
        "ionizationEnergies": [
            6.108
        ],
        "xrayAbsorptionEnergies": {
            "K": 102700
        },
        "xrayEmissionEnergies": {
            "Kα": 87000,
            "Kβ": 102700
        }
    },
    "Pb": {
        "name": "Lead",
        "atomicNumber": 82,
        "group": 14,
        "groupName": "post-transition metal",
        "period": 6,
        "atomicMass": 207.2,
        "stability": "Stable",
        "isotopes": [
            "Pb-204",
            "Pb-206",
            "Pb-207",
            "Pb-208"
        ],
        "electronegativity": 2.33,
        "ionizationEnergies": [
            7.417
        ],
        "xrayAbsorptionEnergies": {
            "K": 105800
        },
        "xrayEmissionEnergies": {
            "Kα": 88000,
            "Kβ": 105800
        }
    },
    "Bi": {
        "name": "Bismuth",
        "atomicNumber": 83,
        "group": 15,
        "groupName": "post-transition metal",
        "period": 6,
        "atomicMass": 208.98,
        "stability": "Stable",
        "isotopes": [
            "Bi-209"
        ],
        "electronegativity": 2.02,
        "ionizationEnergies": [
            7.289
        ],
        "xrayAbsorptionEnergies": {
            "K": 109200
        },
        "xrayEmissionEnergies": {
            "Kα": 92000,
            "Kβ": 109200
        }
    },
    "Po": {
        "name": "Polonium",
        "atomicNumber": 84,
        "group": 16,
        "groupName": "metalloid",
        "period": 6,
        "atomicMass": 209,
        "stability": "Radioactive",
        "isotopes": [
            "Po-209",
            "Po-210"
        ],
        "electronegativity": 2,
        "ionizationEnergies": [
            8.417
        ],
        "xrayAbsorptionEnergies": {
            "K": 112800
        },
        "xrayEmissionEnergies": {
            "Kα": 95000,
            "Kβ": 112800
        }
    },
    "At": {
        "name": "Astatine",
        "atomicNumber": 85,
        "group": 17,
        "groupName": "halogen",
        "period": 6,
        "atomicMass": 210,
        "stability": "Radioactive",
        "isotopes": [
            "At-210"
        ],
        "electronegativity": 2.2,
        "ionizationEnergies": [
            9.3
        ],
        "xrayAbsorptionEnergies": {
            "K": 116800
        },
        "xrayEmissionEnergies": {
            "Kα": 98000,
            "Kβ": 116800
        }
    },
    "Rn": {
        "name": "Radon",
        "atomicNumber": 86,
        "group": 18,
        "groupName": "noble gas",
        "period": 6,
        "atomicMass": 222,
        "stability": "Radioactive",
        "isotopes": [
            "Rn-222"
        ],
        "electronegativity": null,
        "ionizationEnergies": [
            10.748
        ],
        "xrayAbsorptionEnergies": {
            "K": 121000
        },
        "xrayEmissionEnergies": {
            "Kα": 102000,
            "Kβ": 121000
        }
    },
    "Fr": {
        "name": "Francium",
        "atomicNumber": 87,
        "group": 1,
        "groupName": "alkali metal",
        "period": 7,
        "atomicMass": 223,
        "stability": "Radioactive",
        "isotopes": [
            "Fr-223"
        ],
        "electronegativity": 0.7,
        "ionizationEnergies": [
            4.072
        ],
        "xrayAbsorptionEnergies": {
            "K": 125000
        },
        "xrayEmissionEnergies": {
            "Kα": 105000,
            "Kβ": 125000
        }
    },
    "Ra": {
        "name": "Radium",
        "atomicNumber": 88,
        "group": 2,
        "groupName": "alkaline earth metal",
        "period": 7,
        "atomicMass": 226,
        "stability": "Radioactive",
        "isotopes": [
            "Ra-226"
        ],
        "electronegativity": 0.9,
        "ionizationEnergies": [
            5.279
        ],
        "xrayAbsorptionEnergies": {
            "K": 130000
        },
        "xrayEmissionEnergies": {
            "Kα": 108000,
            "Kβ": 130000
        }
    },
    "Ac": {
        "name": "Actinium",
        "atomicNumber": 89,
        "group": "Ac-1",
        "groupName": "actinide",
        "period": 7,
        "atomicMass": 227,
        "stability": "Radioactive",
        "isotopes": [
            "Ac-227"
        ],
        "electronegativity": 1.1,
        "ionizationEnergies": [
            5.17
        ],
        "xrayAbsorptionEnergies": {
            "K": 135000
        },
        "xrayEmissionEnergies": {
            "Kα": 112000,
            "Kβ": 135000
        }
    },
    "Th": {
        "name": "Thorium",
        "atomicNumber": 90,
        "group": "Ac-2",
        "groupName": "actinide",
        "period": 7,
        "atomicMass": 232.04,
        "stability": "Radioactive",
        "isotopes": [
            "Th-232"
        ],
        "electronegativity": 1.3,
        "ionizationEnergies": [
            6.08
        ],
        "xrayAbsorptionEnergies": {
            "K": 140000
        },
        "xrayEmissionEnergies": {
            "Kα": 115000,
            "Kβ": 140000
        }
    },
    "Pa": {
        "name": "Protactinium",
        "atomicNumber": 91,
        "group": "Ac-3",
        "groupName": "actinide",
        "period": 7,
        "atomicMass": 231.04,
        "stability": "Radioactive",
        "isotopes": [
            "Pa-231"
        ],
        "electronegativity": 1.5,
        "ionizationEnergies": [
            5.89
        ],
        "xrayAbsorptionEnergies": {
            "K": 145000
        },
        "xrayEmissionEnergies": {
            "Kα": 118000,
            "Kβ": 145000
        }
    },
    "U": {
        "name": "Uranium",
        "atomicNumber": 92,
        "group": "Ac-4",
        "groupName": "actinide",
        "period": 7,
        "atomicMass": 238.03,
        "stability": "Radioactive",
        "isotopes": [
            "U-234",
            "U-235",
            "U-238"
        ],
        "electronegativity": 1.38,
        "ionizationEnergies": [
            6.19
        ],
        "xrayAbsorptionEnergies": {
            "K": 151000
        },
        "xrayEmissionEnergies": {
            "Kα": 123000,
            "Kβ": 151000
        }
    },
    "Np": {
        "name": "Neptunium",
        "atomicNumber": 93,
        "group": "Ac-5",
        "groupName": "actinide",
        "period": 7,
        "atomicMass": 237,
        "stability": "Radioactive",
        "isotopes": [
            "Np-237"
        ],
        "electronegativity": 1.36,
        "ionizationEnergies": [
            6.27
        ],
        "xrayAbsorptionEnergies": {
            "K": 157000
        },
        "xrayEmissionEnergies": {
            "Kα": 128000,
            "Kβ": 157000
        }
    },
    "Pu": {
        "name": "Plutonium",
        "atomicNumber": 94,
        "group": "Ac-6",
        "groupName": "actinide",
        "period": 7,
        "atomicMass": 244,
        "stability": "Radioactive",
        "isotopes": [
            "Pu-238",
            "Pu-239",
            "Pu-240",
            "Pu-241",
            "Pu-242"
        ],
        "electronegativity": 1.28,
        "ionizationEnergies": [
            6.06
        ],
        "xrayAbsorptionEnergies": {
            "K": 163000
        },
        "xrayEmissionEnergies": {
            "Kα": 133000,
            "Kβ": 163000
        }
    },
    "Am": {
        "name": "Americium",
        "atomicNumber": 95,
        "group": "Ac-7",
        "groupName": "actinide",
        "period": 7,
        "atomicMass": 243,
        "stability": "Radioactive",
        "isotopes": [
            "Am-241",
            "Am-243"
        ],
        "electronegativity": 1.13,
        "ionizationEnergies": [
            5.97
        ],
        "xrayAbsorptionEnergies": {
            "K": 170000
        },
        "xrayEmissionEnergies": {
            "Kα": 138000,
            "Kβ": 170000
        }
    },
    "Cm": {
        "name": "Curium",
        "atomicNumber": 96,
        "group": "Ac-8",
        "groupName": "actinide",
        "period": 7,
        "atomicMass": 247,
        "stability": "Radioactive",
        "isotopes": [
            "Cm-244",
            "Cm-246"
        ],
        "electronegativity": 1.28,
        "ionizationEnergies": [
            5.99
        ],
        "xrayAbsorptionEnergies": {
            "K": 177000
        },
        "xrayEmissionEnergies": {
            "Kα": 143000,
            "Kβ": 177000
        }
    },
    "Bk": {
        "name": "Berkelium",
               "atomicNumber": 97,
        "group": "Ac-9",
        "groupName": "actinide",
        "period": 7,
        "atomicMass": 247,
        "stability": "Radioactive",
        "isotopes": [
            "Bk-247"
        ],
        "electronegativity": 1.3,
        "ionizationEnergies": [
            6.23
        ],
        "xrayAbsorptionEnergies": {
            "K": 184000
        },
        "xrayEmissionEnergies": {
            "Kα": 148000,
            "Kβ": 184000
        }
    },
    "Cf": {
        "name": "Californium",
        "atomicNumber": 98,
        "group": "Ac-10",
        "groupName": "actinide",
        "period": 7,
        "atomicMass": 251,
        "stability": "Radioactive",
        "isotopes": [
            "Cf-249",
            "Cf-252"
        ],
        "electronegativity": 1.3,
        "ionizationEnergies": [
            6.3
        ],
        "xrayAbsorptionEnergies": {
            "K": 191000
        },
        "xrayEmissionEnergies": {
            "Kα": 153000,
            "Kβ": 191000
        }
    },
    "Es": {
        "name": "Einsteinium",
        "atomicNumber": 99,
        "group": "Ac-11",
        "groupName": "actinide",
        "period": 7,
        "atomicMass": 252,
        "stability": "Radioactive",
        "isotopes": [
            "Es-252"
        ],
        "electronegativity": 1.3,
        "ionizationEnergies": [
            6.42
        ],
        "xrayAbsorptionEnergies": {
            "K": 198000
        },
        "xrayEmissionEnergies": {
            "Kα": 158000,
            "Kβ": 198000
        }
    },
    "Fm": {
        "name": "Fermium",
        "atomicNumber": 100,
        "group": "Ac-12",
        "groupName": "actinide",
        "period": 7,
        "atomicMass": 257,
        "stability": "Radioactive",
        "isotopes": [
            "Fm-257"
        ],
        "electronegativity": 1.3,
        "ionizationEnergies": [
            6.5
        ],
        "xrayAbsorptionEnergies": {
            "K": 205000
        },
        "xrayEmissionEnergies": {
            "Kα": 163000,
            "Kβ": 205000
        }
    },
    "Md": {
        "name": "Mendelevium",
        "atomicNumber": 101,
        "group": "Ac-13",
        "groupName": "actinide",
        "period": 7,
        "atomicMass": 258,
        "stability": "Radioactive",
        "isotopes": [
            "Md-258"
        ],
        "electronegativity": 1.3,
        "ionizationEnergies": [
            6.58
        ],
        "xrayAbsorptionEnergies": {
            "K": 212000
        },
        "xrayEmissionEnergies": {
            "Kα": 168000,
            "Kβ": 212000
        }
    },
    "No": {
        "name": "Nobelium",
        "atomicNumber": 102,
        "group": "Ac-14",
        "groupName": "actinide",
        "period": 7,
        "atomicMass": 259,
        "stability": "Radioactive",
        "isotopes": [
            "No-259"
        ],
        "electronegativity": 1.3,
        "ionizationEnergies": [
            6.65
        ],
        "xrayAbsorptionEnergies": {
            "K": 219000
        },
        "xrayEmissionEnergies": {
            "Kα": 173000,
            "Kβ": 219000
        }
    },
    "Lr": {
        "name": "Lawrencium",
        "atomicNumber": 103,
        "group": "Ac-15",
        "groupName": "actinide",
        "period": 7,
        "atomicMass": 262,
        "stability": "Radioactive",
        "isotopes": [
            "Lr-262"
        ],
        "electronegativity": 1.3,
        "ionizationEnergies": [
            4.9
        ],
        "xrayAbsorptionEnergies": {
            "K": 226000
        },
        "xrayEmissionEnergies": {
            "Kα": 178000,
            "Kβ": 226000
        }
    },
    "Rf": {
        "name": "Rutherfordium",
        "atomicNumber": 104,
        "group": 4,
        "groupName": "transition metal",
        "period": 7,
        "atomicMass": 267,
        "stability": "Radioactive",
        "isotopes": [
            "Rf-267"
        ],
        "electronegativity": null,
        "ionizationEnergies": [
            6
        ],
        "xrayAbsorptionEnergies": {
            "K": 233000
        },
        "xrayEmissionEnergies": {
            "Kα": 183000,
            "Kβ": 233000
        }
    },
    "Db": {
        "name": "Dubnium",
        "atomicNumber": 105,
        "group": 5,
        "groupName": "transition metal",
        "period": 7,
        "atomicMass": 268.126,
        "stability": "Radioactive",
        "isotopes": [
            "Db-268"
        ],
        "electronegativity": null,
        "ionizationEnergies": [
            null
        ],
        "xrayAbsorptionEnergies": {
            "K": null
        },
        "xrayEmissionEnergies": {
            "Kα": null,
            "Kβ": null
        }
    },
    "Sg": {
        "name": "Seaborgium",
        "atomicNumber": 106,
        "group": 6,
        "groupName": "transition metal",
        "period": 7,
        "atomicMass": 271,
        "stability": "Radioactive",
        "isotopes": [
            "Sg-271"
        ],
        "electronegativity": null,
        "ionizationEnergies": [
            6.2
        ],
        "xrayAbsorptionEnergies": {
            "K": 247000
        },
        "xrayEmissionEnergies": {
            "Kα": 193000,
            "Kβ": 247000
        }
    },
    "Bh": {
        "name": "Bohrium",
        "atomicNumber": 107,
        "group": 7,
        "groupName": "transition metal",
        "period": 7,
        "atomicMass": 270,
        "stability": "Radioactive",
        "isotopes": [
            "Bh-270"
        ],
        "electronegativity": null,
        "ionizationEnergies": [
            6.3
        ],
        "xrayAbsorptionEnergies": {
            "K": 254000
        },
        "xrayEmissionEnergies": {
            "Kα": 198000,
            "Kβ": 254000
        }
    },
    "Hs": {
        "name": "Hassium",
        "atomicNumber": 108,
        "group": 8,
        "groupName": "transition metal",
        "period": 7,
        "atomicMass": 277,
        "stability": "Radioactive",
        "isotopes": [
            "Hs-277"
        ],
        "electronegativity": null,
        "ionizationEnergies": [
            6.4
        ],
        "xrayAbsorptionEnergies": {
            "K": 261000
        },
        "xrayEmissionEnergies": {
            "Kα": 203000,
            "Kβ": 261000
        }
    },
    "Mt": {
        "name": "Meitnerium",
        "atomicNumber": 109,
        "group": 9,
        "groupName": "transition metal",
        "period": 7,
        "atomicMass": 278,
        "stability": "Radioactive",
        "isotopes": [
            "Mt-278"
        ],
        "electronegativity": null,
        "ionizationEnergies": [
            6.5
        ],
        "xrayAbsorptionEnergies": {
            "K": 268000
        },
        "xrayEmissionEnergies": {
            "Kα": 208000,
            "Kβ": 268000
        }
    },
    "Ds": {
        "name": "Darmstadtium",
        "atomicNumber": 110,
        "group": 10,
        "groupName": "transition metal",
        "period": 7,
        "atomicMass": 281,
        "stability": "Radioactive",
        "isotopes": [
            "Ds-281"
        ],
        "electronegativity": null,
        "ionizationEnergies": [
            6.6
        ],
        "xrayAbsorptionEnergies": {
            "K": 275000
        },
        "xrayEmissionEnergies": {
            "Kα": 213000,
            "Kβ": 275000
        }
    },
    "Rg": {
        "name": "Roentgenium",
        "atomicNumber": 111,
        "group": 11,
        "groupName": "transition metal",
        "period": 7,
        "atomicMass": 282,
        "stability": "Radioactive",
        "isotopes": [
            "Rg-282"
        ],
        "electronegativity": null,
        "ionizationEnergies": [
            6.7
        ],
        "xrayAbsorptionEnergies": {
            "K": 282000
        },
        "xrayEmissionEnergies": {
            "Kα": 218000,
            "Kβ": 282000
        }
    },
    "Cn": {
        "name": "Copernicium",
        "atomicNumber": 112,
        "group": 12,
        "groupName": "transition metal",
        "period": 7,
        "atomicMass": 285,
        "stability": "Radioactive",
        "isotopes": [
            "Cn-285"
        ],
        "electronegativity": null,
        "ionizationEnergies": [
            7
        ],
        "xrayAbsorptionEnergies": {
            "K": 289000
        },
        "xrayEmissionEnergies": {
            "Kα": 223000,
            "Kβ": 289000
        }
    },
    "Nh": {
        "name": "Nihonium",
        "atomicNumber": 113,
        "group": 13,
        "groupName": "post-transition metal",
        "period": 7,
        "atomicMass": 286,
        "stability": "Radioactive",
        "isotopes": [
            "Nh-286"
        ],
        "electronegativity": null,
        "ionizationEnergies": [
            7.3
        ],
        "xrayAbsorptionEnergies": {
            "K": 296000
        },
        "xrayEmissionEnergies": {
            "Kα": 228000,
            "Kβ": 296000
        }
    },
    "Fl": {
        "name": "Flerovium",
        "atomicNumber": 114,
        "group": 14,
        "groupName": "post-transition metal",
        "period": 7,
        "atomicMass": 289,
        "stability": "Radioactive",
        "isotopes": [
            "Fl-289"
        ],
        "electronegativity": null,
        "ionizationEnergies": [
            7.4
        ],
        "xrayAbsorptionEnergies": {
            "K": 303000
        },
        "xrayEmissionEnergies": {
            "Kα": 233000,
            "Kβ": 303000
        }
    },
    "Mc": {
        "name": "Moscovium",
        "atomicNumber": 115,
        "group": 15,
        "groupName": "post-transition metal",
        "period": 7,
        "atomicMass": 290,
        "stability": "Radioactive",
        "isotopes": [
            "Mc-290"
        ],
        "electronegativity": null,
        "ionizationEnergies": [
            7.7
        ],
        "xrayAbsorptionEnergies": {
            "K": 310000
        },
        "xrayEmissionEnergies": {
            "Kα": 238000,
            "Kβ": 310000
        }
    },
    "Lv": {
        "name": "Livermorium",
        "atomicNumber": 116,
        "group": 16,
        "groupName": "post-transition metal",
        "period": 7,
        "atomicMass": 293,
        "stability": "Radioactive",
        "isotopes": [
            "Lv-293"
        ],
        "electronegativity": null,
        "ionizationEnergies": [
            7.9
        ],
        "xrayAbsorptionEnergies": {
            "K": 317000
        },
        "xrayEmissionEnergies": {
            "Kα": 243000,
            "Kβ": 317000
        }
    },
    "Ts": {
        "name": "Tennessine",
        "atomicNumber": 117,
        "group": 17,
        "groupName": "halogen",
        "period": 7,
        "atomicMass": 294,
        "stability": "Radioactive",
        "isotopes": [
            "Ts-294"
        ],
        "electronegativity": null,
        "ionizationEnergies": [
            8
        ],
        "xrayAbsorptionEnergies": {
            "K": 324000
        },
        "xrayEmissionEnergies": {
            "Kα": 248000,
            "Kβ": 324000
        }
    },
    "Og": {
        "name": "Oganesson",
        "atomicNumber": 118,
        "group": 18,
        "groupName": "noble gas",
        "period": 7,
        "atomicMass": 294,
        "stability": "Radioactive",
        "isotopes": [
            "Og-294"
        ],
        "electronegativity": null,
        "ionizationEnergies": [
            8
        ],
        "xrayAbsorptionEnergies": {
            "K": 331000
        },
        "xrayEmissionEnergies": {
            "Kα": 253000,
            "Kβ": 331000
        }
    }
};
